#!/bin/bash

#### add-apt-repository requires python-software-properties
sudo apt-get install -y python-software-properties

#### language support
sudo apt-get install -y language-pack-en

# JA-Localized for Ubuntu11.10
wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | sudo apt-key add -
wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | sudo apt-key add -
sudo wget https://www.ubuntulinux.jp/sources.list.d/oneiric.list -O /etc/apt/sources.list.d/ubuntu-ja.list
sudo wget https://www.ubuntulinux.jp/fonts.conf.d/oneiric-69-language-selector-ja-jp.conf -O /etc/fonts/conf.avail/69-language-selector-ja-jp.conf
sudo fontconfig-voodoo -s ja_JP

#### desktop utilities
sudo apt-get install -y clamtk
sudo apt-get install -y gufw
sudo apt-get install -y compizconfig-settings-manager
sudo apt-get install -y ibus-mozc
sudo apt-get install -y indicator-multiload
sudo apt-get install -y libnotify-bin
sudo apt-get install -y impressive
# for opera japanese input
sudo apt-get install -y ibus-qt4
# fonts
sudo apt-get install -y ttf-inconsolata
sudo apt-get install -y ttf-vlgothic
# font utilities
sudo apt-get install -y fontforge

#### cli utilities
sudo apt-get install -y byobu
sudo apt-get install -y sysv-rc-conf
sudo apt-get install -y curl
sudo apt-get install -y nmap
sudo apt-get install -y make
sudo apt-get install -y source-highlight
sudo apt-get install -y nkf
sudo apt-get install -y optipng
sudo apt-get install -y festival
sudo apt-get install -y rlwrap

#### development tools
sudo apt-get install -y subversion
sudo apt-get install -y git
sudo apt-get install -y git-svn
sudo apt-get install -y tig
sudo apt-get install -y meld

#### editors
sudo apt-get install -y vim
